Repository GetJobber/help_theme_2019, pull requests merged in 2023-02, with the labels that each got.

#54 Banner Hotfix, YouTube redirect
  manifest.json
  package-lock.json
  script.js
  templates/header.hbs
Labels: Team Marketing Devs, approved

#56 update video manual title on home page
  manifest.json
  templates/home_page.hbs
Labels: PTAL, approved

#55 Adding in redirect numbers
  script.js
Labels: PTAL, Team Marketing Devs, approved
